### ISSUE TITLE
custom theme settings sometimes don't behave as expected？

### ISSUE THREAD

**Issue by DaaMeiling** [nhn/tui.calendar#1036]
## Summary

Not all styles of the default theme work as expect, even I set custom theme.
it seems that **"month.dayExceptThisMonth.color"** didn't work💔
I create a demo that you can see.

https://codesandbox.io/s/silly-ishizaka-588jtx?file=/src/components/HelloWorld.vue:597-629

If my configuration is wrong, please correct me～

## Version
"vue": "^3.2.31",
 "tui-calendar": "1.15.3",
   "tui-date-picker": "^4.3.1",
   "tui-time-picker": "^2.1.4",

**Comment by adhrinae** [comment]
@DaaMeiling 
I'm not a vue expert so not sure where the problem comes from, but the calendar instance outside Vue shows the theme properly.

Why don't you try the [vue wrapper](https://github.com/nhn/toast-ui.vue-calendar) instead? Let's find out deeper if there's still the problem with the wrapper.
