### ISSUE TITLE
How to DragnDrop events in Daily Calendar Mode?

### ISSUE THREAD

**Issue by 99bits** [nhn/tui.calendar#1119]
Hi, 

Thank you for making this amazing project.  

I am using the Daily Calendar mode and would like to Add/Delete and Rearrange the events.
Is this possible to do?

Thank you

**Comment by adhrinae** [comment]
@99bits 

Yes, you can.

There are methods to manipulate schedules.

https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#manipulate-schedules

You should bind some events so that you can call methods right after drag & drop.

- https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule
- https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeDeleteSchedule
- https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeUpdateSchedule

And you can enable the `useCreationPopup` option to use the default popup. Otherwise, you need to implement your logic to create schedules.
