### ISSUE TITLE
Which source should I refer to see the allday toggle function?

### ISSUE THREAD

**Issue by cheeseblossom** [nhn/tui.calendar#1233]
First of all, I would like to thank you for providing the tui calendar.

As I use it, when I check allday, there is a phenomenon that the title and location are initialized. Where should I look in js?

I don't want it to be initialized

**Comment by adhrinae** [comment]
@cheeseblossom 
I'm not sure what you're asking. Could you give me an example code and detailed steps for the problem?

**Comment by cheeseblossom** [comment]
I'm using it based on an example.

![1.png](https://user-images.githubusercontent.com/59395805/181678098-9c0a7508-c71d-4e17-ae50-ce317d33620a.png)

result..

![2.png](https://user-images.githubusercontent.com/59395805/181678116-1be304be-e9d8-42fb-a8fe-21dcb99b3988.png)

Enter the title and location as shown in the image and check allday to reset the entered value.
I want to make sure this doesn't happen.

**Comment by adhrinae** [comment]
@cheeseblossom
I see. It's an internal bug of the popup. So there's no point in fixing this in the example code.

**Comment by cheeseblossom** [comment]
Okay.
So can you tell me where to look in the toastui-calendar.js file? There are a lot of complaints about this phenomenon and I need to address it.

Since toastui-calendar.js was modified to use items other than subject and location, I will have to work again if you upgrade. I would like to modify the current source to prevent this.

**Comment by adhrinae** [comment]
@cheeseblossom 

The easiest way to resolve this problem is to wrap the components below with the `memo` function.

- https://github.com/nhn/tui.calendar/blob/main/apps/calendar/src/components/popup/locationInputBox.tsx
- https://github.com/nhn/tui.calendar/blob/main/apps/calendar/src/components/popup/titleInputBox.tsx

Since you're modifying the bundled file directly, you can search components by their name and wrap them with the `compat_module_g` function.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/14539203/181698527-52b9e989-f626-4fa5-aac9-4c0a9657fed4.png">

Do the same thing to the `TitleInputBox`.

**Comment by cheeseblossom** [comment]
@adhrinae 

Solved.
Thank you for your help.
