### ISSUE TITLE
setDate not working in safari

### ISSUE THREAD

**Issue by rAndroidTest** [nhn/tui.calendar#1307]
Version - 1.13

Tested on windows and mac - works fine on windows (chrome etc) not workin in safari on mac

Taking a string say Oct 2022 and then converting to date with 

let dateToMove = new Date(“Oct 2022”);
calendarInstace.setDate(dateToMove);

works fine in chrome, but gives no data in Safari 

I have tried the following:

let dateToMove = moment(“Oct 2022”).toDate().toISOString();
calendarInstance.setDate(dateToMove);

I get invalid input doesn’t work on chrome or safari

I tried:
let dateToMove = moment(“Oct 2022”).toDate():
calendarInstance.setDate(dateToMove);

Again works in chrome not safari.

Any ideas how to get setDate to work in both?

thanks!

**Comment by adhrinae** [comment]
The calendar uses the native `Date` type internally. so you must check out how to create a `Date` instance correctly.

I recommend following the ISO 8601 format to make any `Date` instances. Otherwise, you'll find it hard to get correct results.

- https://tc39.es/ecma262/#sec-date-time-string-format
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#several_ways_to_create_a_date_object

**Comment by rAndroidTest** [comment]
I tried 

    let dateToMove = new Date('YYYY-MM-DDTHH:mm:ss.sssZ',e.target.value);
    console.log(dateToMove);
    calendarInstance.setDate(dateToMove);

as well as

    let dateToMove = new Date(e.target.value);
    let newDate  = date.toISOString();
    console.log(newDate);
    calendarInstance.setDate(newDate);

Both give me Uncaught Error: Invalid Type In all browsers

**Comment by adhrinae** [comment]
Again, It's not the calendar's problem. you need to understand the basic usage of Javascript's `Date` type. Looks like you don't understand it.

**Comment by rAndroidTest** [comment]
guess not thanks for the help
