### ISSUE TITLE
Is it possible to show all schedule without show more button ?

### ISSUE THREAD

**Issue by serip88** [nhn/tui.calendar#295]
## Version
version 1.8.1

## Development Environment
browser chrome, window

## Expected Behavior
Hi,
Is it possible show all schedule without show more button ?
I mean visibleScheduleCount = 100 not working, because it limited by grid height

Thanks and Regards

**Comment by itsfaqih** [comment]
Hi, I'd like to hear the answer of this question. I already tried to set `visibleScheduleCount`, but it only shown 3 max

![image](https://user-images.githubusercontent.com/48067039/105320777-2921d700-5bf9-11eb-9a35-2ba79e79d7ce.png)

![image](https://user-images.githubusercontent.com/48067039/105320812-38a12000-5bf9-11eb-975e-c7296acba4ba.png)

Since I'm using the react version, I don't know if it's the same for this version

**Comment by jungeun-cho** [comment]
@itsfaqih This is the bug.
Sufficient height must be secured for the schedule to be displayed.
Otherwise, the grid will draw a schedule with the same height.

**Comment by itsfaqih** [comment]
I see. Thanks for answering! It works 😄

**Comment by scratchoo** [comment]
is this ever solved?  it's really limiting to not be able to show all the events in a box, the calendar should auto grow
