### ISSUE TITLE
Document usage of recurrenceRule

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#486]
The format and purpose of the data in the `recurrenceRule` is not clear for me, neither after looking at the examples nor after reading the documentation.  My understanding of the purpose of a Recurrence Rule is the one described in the [iCalendar specification for RRULE](https://tools.ietf.org/html/rfc5545#section-3.3.10).

**Comment by jungeun-cho** [comment]
check #371

**Comment by Volmarg** [comment]
I will just leave info for other since I searched for solution as well:

I've used this parameter indeed, just had to attach logic to events for create/update and modify the popup on-fly, by adding `MutationListener` on the popup.

![image](https://user-images.githubusercontent.com/37488679/112715055-4cf5e780-8ede-11eb-9fa8-236fbdfeea40.png)
