### ISSUE TITLE
How to increase number of schedules in a day

### ISSUE THREAD

**Issue by joyjo** [nhn/tui.calendar#494]
Hello,

I am using monthly view. So I want to increase number of schedules in a day.  Now its only 2.  
Is it possible?

thank you.

**Comment by jungeun-cho** [comment]
The monthly view adjusts the number of events shown in one box based on the overall calendar height.
When the height decreases, it is automatically adjusted so that you can see in the more layer by clicking the more button.

https://nhn.github.io/tui.calendar/latest/tutorial-example01-monthly

Please keep the issue template.

**Comment by dongsik-yoo** [comment]
And see this [MonthOptions.visibleScheduleCount](https://nhn.github.io/tui.calendar/latest/MonthOptions) option too.

**Comment by dariusz-hub** [comment]
Is it possible to achieve such an effect that all meetings are displayed and the line height is calculated automatically?


actual
![Screenshot_2020-07-29](https://user-images.githubusercontent.com/53866006/88810831-27310b00-d1b6-11ea-8d60-0c2aca5650e3.png)

expected
![unknown](https://user-images.githubusercontent.com/53866006/88810643-ecc76e00-d1b5-11ea-8036-c8d5f2f70b32.png)
