### ISSUE TITLE
Is there a way to force open details popup from own event?

### ISSUE THREAD

**Issue by david-puente** [nhn/tui.calendar#555]
## Summary
From my own event I want to open the schedule detail popup. Is there some way?

## Version
version 1.12.10

**Comment by jungeun-cho** [comment]
Do you want to open a detailed popup without a mouse click?
if not,
Do you want to use your custom detail popup when clicked?

Can you write it in more detail?

**Comment by david-puente** [comment]
I want to open a detailed popup when something happens in my code's logic, for example when the event time has come.

**Comment by andrelung** [comment]
@david-puente did you find a way to do this? I tried 
`getElement(eventId, calendarId).click()`

but the click does not seem to be working.

**Comment by adhrinae** [comment]
(⚠️ This comment explains the behavior of v2, not v1)

@andrelung 

Yeah, because it does accept from the `mousedown` to `mouseup` events, not the `click` event. The `.click()` method only dispatches [the click event](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event).

We're not going to make an API to open the details popup soon, however, There's an escape hatch to control the calendar's internal state.

```js
// suppose you have a calendar instance called `cal`.
const eventEl = cal.getElement(eventId, calendarId);
const eventObject = cal.getEvent(eventId, calendarId); // we need the data of the event

const eventElRect = el.getBoundingClientRect();
const showDetailsPouup = cal.getStoreDispatchers().popup.showDetailPopup

showDetailsPopup({
  event: eventObject,
  eventRect: eventElRect,
}, false) // set it `true` if you're opening popup of the event inside the 'see more' popup
```

Working example: https://playcode.io/953125/
