### ISSUE TITLE
CalendarList DDL in NewSchedule Popup customized available?

### ISSUE THREAD

**Issue by sam551875** [nhn/tui.calendar#560]
Hi, dear devs :100: 

How can I customize the CalendarList DDL in NewSchedule Popup, I want to limit some calendars that are not able to be newed by users.

For examlple, if here are three calendars (Calendar1, Calendar2, Calendar3) in this Calendar System, only Calendar2 and Calendar3 can new Schedules, then after I click New Schedule button, only Calendar2 and Calendar3 would appear in the Calendar DropdownList (red box marked in image below), and without seeing Calendar1.

![GithubQ](https://user-images.githubusercontent.com/51784878/78633142-5c49e280-78d3-11ea-9323-9807ca3d0160.PNG)

Thanks for helping!

**Comment by jungeun-cho** [comment]
In the TOAST UI calendar, only the schedule data is managed, and the calendar data is not managed separately.

https://nhn.github.io/tui.calendar/latest/Calendar#setCalendars

You can set the calendar list using `cal.setCalendars`.

In order to customize the drop-down list in the default popup, I think you have to create your own custom popup.

**Comment by sam551875** [comment]
Thanks for your responding! This issue has been bothering me for few days.

 I'll try as you suggest. : )
