### ISSUE TITLE
Dynamic Height of Weeks in Month View

### ISSUE THREAD

**Issue by ecwoska** [nhn/tui.calendar#747]
## Summary
In the Hide Weekends example, is it possible to dynamically set the height of each row (i.e., week) based on the maximum number of events in any given day? I see the current logic does the opposite and determines the "exceed" count based on the height of the container.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
1.12.14 | Tue Sep 22 2020

**Comment by jungeun-cho** [comment]
@ecwoska 
The height is fixed.
The reason is that the calendar has a layout algorithm for rendering events.

If you have a lot of event, you can use the [2 weeks view](https://nhn.github.io/tui.calendar/latest/tutorial-example04-2-weeks) and [3 weeks view](https://nhn.github.io/tui.calendar/latest/tutorial-example05-3-weeks).
