### ISSUE TITLE
Create Schedule Popup Inside a Modal

### ISSUE THREAD

**Issue by fabiofahri** [nhn/tui.calendar#862]
Hello,

So, I want to customize how we create the schedule. 

Is it possible to make the create schedule popup inside modal?

This is the example, I got this by copy-paste the code from inspect element, so the dropdown and date picker is not working.

![image](https://user-images.githubusercontent.com/67059228/125386580-b71b9500-e3c6-11eb-9964-9c98bbd788b8.png)

**Comment by adhrinae** [comment]
@fabiofahri I'm afraid you cannot set the arbitrary position where the popup appears through the option.

So, your approach is kind of the only way to implement a creation popup inside a modal.
What you need to know is that the default creation popup relies on [`tui-date-picker`](https://github.com/nhn/tui.date-picker) package. Otherwise, you need to implement your own date picker.

[You can refer this source code.](http://github.com/nhn/tui.calendar/blob/62158bc4d711fbfd82a27e8ac213df7c562ea49b/src/js/view/popup/scheduleCreationPopup.js#L595-L617)
