### ISSUE TITLE
Class: private / public, in the raw element of the schedule does not get updated.

### ISSUE THREAD

**Issue by ilija-jovev** [nhn/tui.calendar#927]
When I create the schedule I can click on the lock icon which adds "class: private" in the "raw" element of scheduleData. However, when I try to update the same schedule afterwards - nothing happens. The "changes" object in the beforeUpdateSchedule function is null if I don't change something else in the pop-up, apart from just clicking the icon. 

What I'm ultimately trying to accomplish is to have a schedule event which the user won't be able to drag (like the read-only schedules), but will be able to edit (unlike the read-only schedules), and after editing if they change this property - it becomes draggable again. I'm considering using the lock icon for this. Please let me know If there's a better way to accomplish something similar.

Thanks

**Comment by adhrinae** [comment]
@ilija-jovev 
It's clearly a bug. I'm not sure why I cannot find any related issue, But it was a bug at the beginning.
Rather than assigning `class: private | public` on the `raw` field, we can leverage the `isPrivate` property in the `Schedule` model.

After that, when you toggle the lock icon and save the change, the event object will be like this.

```
{
  ...
  changes: {
    isPrivate: true | false
    ...
  }
}
```

Would it be okay with you?

**Comment by ilija-jovev** [comment]
Yes, that would be perfect, thanks

**Comment by adhrinae** [comment]
@ilija-jovev 
The fixed version has been publised. Please try `v1.15.1`.
