### ISSUE TITLE
Support Angular 10+ 

### ISSUE THREAD

**Issue by ezequiel88** [nhn/tui.calendar#950]
Congratulations on the work. How is the compatibility with Angular 10+? It's possible?

**Comment by adhrinae** [comment]
@ezequiel88 
We don't officially support Angular wrapper for this project.
But since it's just a javascript library interacting with the DOM, you can leverage it in your Angular project.

I made a simple demo importing the calendar into an Angular project.

https://stackblitz.com/edit/angular-ivy-d9ccxi?file=src/app/app.component.ts

I know nothing about Angular so there might be the best way to access DOM in Angular, but you can get the point.
